### ISSUE TITLE
:bug: 运行时间较长后 关闭队列/日志相关按钮点不动 日志界面无法滑动

### ISSUE THREAD

**Issue by insider-charlie** [3lang3/wave-desktop-release#2]
数量: 约5000+条
时间: 约1h以上
并发数: 30
缓存超时: 0.1
队列重复: 10
队列间隔: 2

**Comment by 3lang3** [comment]
优化后:

- 全部标签最多5000条数据
- 移除信息标签
- 成功，报错，警告标签独立记数不受条数限制

已修复v0.0.0-dev20
